"""Arrow Flight protocol messages, trimmed and wire-compatible.

Generated by tools/proto_gen.py from /Volumes/ExtNVMe/dev/magmalake/flight.mojo/proto/flight.proto.
Do not edit by hand; regenerate from the .proto source.
"""

from std.collections import List, Optional
from std.collections.span import Span

from flare.grpc.proto import (
    ProtoReader,
    ProtoWriter,
    WIRE_I32,
    WIRE_I64,
    WIRE_LEN,
    WIRE_VARINT,
)
from flare.grpc import (
    GrpcBidiStream,
    GrpcBidiStreaming,
    GrpcCallContext,
    GrpcClient,
    GrpcClientStreaming,
    GrpcServerStream,
    GrpcServerStreamReply,
    GrpcServerStreaming,
    GrpcUnary,
    GrpcUnaryReply,
)


struct HandshakeRequest(Copyable, Movable):
    """Generated proto3 message ``HandshakeRequest``."""

    var protocol_version: UInt64
    var payload: List[UInt8]

    def __init__(out self):
        self.protocol_version = 0
        self.payload = List[UInt8]()

    def encode(self) raises -> List[UInt8]:
        var w = ProtoWriter()
        if self.protocol_version != 0:
            w.write_uint64(1, self.protocol_version)
        if len(self.payload) > 0:
            w.write_bytes(2, Span[UInt8, _](self.payload))
        return w.take()

    @staticmethod
    def decode(data: Span[UInt8, _]) raises -> Self:
        var out = Self()
        var r = ProtoReader(data)
        while r.has_more():
            var tw = r.read_tag()
            var field = tw[0]
            var wire = tw[1]
            if field == 1 and wire == WIRE_VARINT:
                out.protocol_version = r.read_uint64()
            elif field == 2 and wire == WIRE_LEN:
                out.payload = r.read_bytes()
            else:
                r.skip(wire)
        return out^


struct HandshakeResponse(Copyable, Movable):
    """Generated proto3 message ``HandshakeResponse``."""

    var protocol_version: UInt64
    var payload: List[UInt8]

    def __init__(out self):
        self.protocol_version = 0
        self.payload = List[UInt8]()

    def encode(self) raises -> List[UInt8]:
        var w = ProtoWriter()
        if self.protocol_version != 0:
            w.write_uint64(1, self.protocol_version)
        if len(self.payload) > 0:
            w.write_bytes(2, Span[UInt8, _](self.payload))
        return w.take()

    @staticmethod
    def decode(data: Span[UInt8, _]) raises -> Self:
        var out = Self()
        var r = ProtoReader(data)
        while r.has_more():
            var tw = r.read_tag()
            var field = tw[0]
            var wire = tw[1]
            if field == 1 and wire == WIRE_VARINT:
                out.protocol_version = r.read_uint64()
            elif field == 2 and wire == WIRE_LEN:
                out.payload = r.read_bytes()
            else:
                r.skip(wire)
        return out^


struct FlightDescriptor(Copyable, Movable):
    """Generated proto3 message ``FlightDescriptor``."""

    var type: Int64
    var cmd: List[UInt8]
    var path: List[String]

    def __init__(out self):
        self.type = 0
        self.cmd = List[UInt8]()
        self.path = List[String]()

    def encode(self) raises -> List[UInt8]:
        var w = ProtoWriter()
        if self.type != 0:
            w.write_int64(1, self.type)
        if len(self.cmd) > 0:
            w.write_bytes(2, Span[UInt8, _](self.cmd))
        for i in range(len(self.path)):
            w.write_string(3, self.path[i])
        return w.take()

    @staticmethod
    def decode(data: Span[UInt8, _]) raises -> Self:
        var out = Self()
        var r = ProtoReader(data)
        while r.has_more():
            var tw = r.read_tag()
            var field = tw[0]
            var wire = tw[1]
            if field == 1 and wire == WIRE_VARINT:
                out.type = r.read_int64()
            elif field == 2 and wire == WIRE_LEN:
                out.cmd = r.read_bytes()
            elif field == 3 and wire == WIRE_LEN:
                out.path.append(r.read_string())
            else:
                r.skip(wire)
        return out^


struct Location(Copyable, Movable):
    """Generated proto3 message ``Location``."""

    var uri: String

    def __init__(out self):
        self.uri = String("")

    def encode(self) raises -> List[UInt8]:
        var w = ProtoWriter()
        if self.uri.byte_length() > 0:
            w.write_string(1, self.uri)
        return w.take()

    @staticmethod
    def decode(data: Span[UInt8, _]) raises -> Self:
        var out = Self()
        var r = ProtoReader(data)
        while r.has_more():
            var tw = r.read_tag()
            var field = tw[0]
            var wire = tw[1]
            if field == 1 and wire == WIRE_LEN:
                out.uri = r.read_string()
            else:
                r.skip(wire)
        return out^


struct Ticket(Copyable, Movable):
    """Generated proto3 message ``Ticket``."""

    var ticket: List[UInt8]

    def __init__(out self):
        self.ticket = List[UInt8]()

    def encode(self) raises -> List[UInt8]:
        var w = ProtoWriter()
        if len(self.ticket) > 0:
            w.write_bytes(1, Span[UInt8, _](self.ticket))
        return w.take()

    @staticmethod
    def decode(data: Span[UInt8, _]) raises -> Self:
        var out = Self()
        var r = ProtoReader(data)
        while r.has_more():
            var tw = r.read_tag()
            var field = tw[0]
            var wire = tw[1]
            if field == 1 and wire == WIRE_LEN:
                out.ticket = r.read_bytes()
            else:
                r.skip(wire)
        return out^


struct FlightEndpoint(Copyable, Movable):
    """Generated proto3 message ``FlightEndpoint``."""

    var ticket: Optional[Ticket]
    var location: List[Location]

    def __init__(out self):
        self.ticket = Optional[Ticket]()
        self.location = List[Location]()

    def encode(self) raises -> List[UInt8]:
        var w = ProtoWriter()
        if Bool(self.ticket):
            w.write_message(1, Span[UInt8, _](self.ticket.value().encode()))
        for i in range(len(self.location)):
            w.write_message(2, Span[UInt8, _](self.location[i].encode()))
        return w.take()

    @staticmethod
    def decode(data: Span[UInt8, _]) raises -> Self:
        var out = Self()
        var r = ProtoReader(data)
        while r.has_more():
            var tw = r.read_tag()
            var field = tw[0]
            var wire = tw[1]
            if field == 1 and wire == WIRE_LEN:
                out.ticket = Optional[Ticket](Ticket.decode(Span[UInt8, _](r.read_bytes())))
            elif field == 2 and wire == WIRE_LEN:
                out.location.append(Location.decode(Span[UInt8, _](r.read_bytes())))
            else:
                r.skip(wire)
        return out^


struct FlightInfo(Copyable, Movable):
    """Generated proto3 message ``FlightInfo``."""

    var schema: List[UInt8]
    var flight_descriptor: Optional[FlightDescriptor]
    var endpoint: List[FlightEndpoint]
    var total_records: Int64
    var total_bytes: Int64
    var ordered: Bool
    var app_metadata: List[UInt8]

    def __init__(out self):
        self.schema = List[UInt8]()
        self.flight_descriptor = Optional[FlightDescriptor]()
        self.endpoint = List[FlightEndpoint]()
        self.total_records = 0
        self.total_bytes = 0
        self.ordered = False
        self.app_metadata = List[UInt8]()

    def encode(self) raises -> List[UInt8]:
        var w = ProtoWriter()
        if len(self.schema) > 0:
            w.write_bytes(1, Span[UInt8, _](self.schema))
        if Bool(self.flight_descriptor):
            w.write_message(2, Span[UInt8, _](self.flight_descriptor.value().encode()))
        for i in range(len(self.endpoint)):
            w.write_message(3, Span[UInt8, _](self.endpoint[i].encode()))
        if self.total_records != 0:
            w.write_int64(4, self.total_records)
        if self.total_bytes != 0:
            w.write_int64(5, self.total_bytes)
        if self.ordered:
            w.write_bool(6, self.ordered)
        if len(self.app_metadata) > 0:
            w.write_bytes(7, Span[UInt8, _](self.app_metadata))
        return w.take()

    @staticmethod
    def decode(data: Span[UInt8, _]) raises -> Self:
        var out = Self()
        var r = ProtoReader(data)
        while r.has_more():
            var tw = r.read_tag()
            var field = tw[0]
            var wire = tw[1]
            if field == 1 and wire == WIRE_LEN:
                out.schema = r.read_bytes()
            elif field == 2 and wire == WIRE_LEN:
                out.flight_descriptor = Optional[FlightDescriptor](FlightDescriptor.decode(Span[UInt8, _](r.read_bytes())))
            elif field == 3 and wire == WIRE_LEN:
                out.endpoint.append(FlightEndpoint.decode(Span[UInt8, _](r.read_bytes())))
            elif field == 4 and wire == WIRE_VARINT:
                out.total_records = r.read_int64()
            elif field == 5 and wire == WIRE_VARINT:
                out.total_bytes = r.read_int64()
            elif field == 6 and wire == WIRE_VARINT:
                out.ordered = r.read_bool()
            elif field == 7 and wire == WIRE_LEN:
                out.app_metadata = r.read_bytes()
            else:
                r.skip(wire)
        return out^


struct Criteria(Copyable, Movable):
    """Generated proto3 message ``Criteria``."""

    var expression: List[UInt8]

    def __init__(out self):
        self.expression = List[UInt8]()

    def encode(self) raises -> List[UInt8]:
        var w = ProtoWriter()
        if len(self.expression) > 0:
            w.write_bytes(1, Span[UInt8, _](self.expression))
        return w.take()

    @staticmethod
    def decode(data: Span[UInt8, _]) raises -> Self:
        var out = Self()
        var r = ProtoReader(data)
        while r.has_more():
            var tw = r.read_tag()
            var field = tw[0]
            var wire = tw[1]
            if field == 1 and wire == WIRE_LEN:
                out.expression = r.read_bytes()
            else:
                r.skip(wire)
        return out^


struct FlightData(Copyable, Movable):
    """Generated proto3 message ``FlightData``."""

    var flight_descriptor: Optional[FlightDescriptor]
    var data_header: List[UInt8]
    var app_metadata: List[UInt8]
    var data_body: List[UInt8]

    def __init__(out self):
        self.flight_descriptor = Optional[FlightDescriptor]()
        self.data_header = List[UInt8]()
        self.app_metadata = List[UInt8]()
        self.data_body = List[UInt8]()

    def encode(self) raises -> List[UInt8]:
        var w = ProtoWriter()
        if Bool(self.flight_descriptor):
            w.write_message(1, Span[UInt8, _](self.flight_descriptor.value().encode()))
        if len(self.data_header) > 0:
            w.write_bytes(2, Span[UInt8, _](self.data_header))
        if len(self.app_metadata) > 0:
            w.write_bytes(3, Span[UInt8, _](self.app_metadata))
        if len(self.data_body) > 0:
            w.write_bytes(1000, Span[UInt8, _](self.data_body))
        return w.take()

    @staticmethod
    def decode(data: Span[UInt8, _]) raises -> Self:
        var out = Self()
        var r = ProtoReader(data)
        while r.has_more():
            var tw = r.read_tag()
            var field = tw[0]
            var wire = tw[1]
            if field == 1 and wire == WIRE_LEN:
                out.flight_descriptor = Optional[FlightDescriptor](FlightDescriptor.decode(Span[UInt8, _](r.read_bytes())))
            elif field == 2 and wire == WIRE_LEN:
                out.data_header = r.read_bytes()
            elif field == 3 and wire == WIRE_LEN:
                out.app_metadata = r.read_bytes()
            elif field == 1000 and wire == WIRE_LEN:
                out.data_body = r.read_bytes()
            else:
                r.skip(wire)
        return out^


struct SchemaResult(Copyable, Movable):
    """Generated proto3 message ``SchemaResult``."""

    var schema: List[UInt8]

    def __init__(out self):
        self.schema = List[UInt8]()

    def encode(self) raises -> List[UInt8]:
        var w = ProtoWriter()
        if len(self.schema) > 0:
            w.write_bytes(1, Span[UInt8, _](self.schema))
        return w.take()

    @staticmethod
    def decode(data: Span[UInt8, _]) raises -> Self:
        var out = Self()
        var r = ProtoReader(data)
        while r.has_more():
            var tw = r.read_tag()
            var field = tw[0]
            var wire = tw[1]
            if field == 1 and wire == WIRE_LEN:
                out.schema = r.read_bytes()
            else:
                r.skip(wire)
        return out^


comptime FLIGHT_PROTO_FILENAME: StaticString = "flight.proto"

def flight_file_descriptor() -> List[UInt8]:
    """Serialized FileDescriptorProto for ``flight.proto`` (reflection)."""
    var out: List[UInt8] = [
        10, 12, 102, 108, 105, 103, 104, 116, 46, 112, 114, 111, 116, 111, 18, 21,
        97, 114, 114, 111, 119, 46, 102, 108, 105, 103, 104, 116, 46, 112, 114, 111,
        116, 111, 99, 111, 108, 34, 61, 10, 16, 72, 97, 110, 100, 115, 104, 97,
        107, 101, 82, 101, 113, 117, 101, 115, 116, 18, 24, 10, 16, 112, 114, 111,
        116, 111, 99, 111, 108, 95, 118, 101, 114, 115, 105, 111, 110, 24, 1, 32,
        1, 40, 4, 18, 15, 10, 7, 112, 97, 121, 108, 111, 97, 100, 24, 2,
        32, 1, 40, 12, 34, 62, 10, 17, 72, 97, 110, 100, 115, 104, 97, 107,
        101, 82, 101, 115, 112, 111, 110, 115, 101, 18, 24, 10, 16, 112, 114, 111,
        116, 111, 99, 111, 108, 95, 118, 101, 114, 115, 105, 111, 110, 24, 1, 32,
        1, 40, 4, 18, 15, 10, 7, 112, 97, 121, 108, 111, 97, 100, 24, 2,
        32, 1, 40, 12, 34, 59, 10, 16, 70, 108, 105, 103, 104, 116, 68, 101,
        115, 99, 114, 105, 112, 116, 111, 114, 18, 12, 10, 4, 116, 121, 112, 101,
        24, 1, 32, 1, 40, 5, 18, 11, 10, 3, 99, 109, 100, 24, 2, 32,
        1, 40, 12, 18, 12, 10, 4, 112, 97, 116, 104, 24, 3, 32, 3, 40,
        9, 34, 23, 10, 8, 76, 111, 99, 97, 116, 105, 111, 110, 18, 11, 10,
        3, 117, 114, 105, 24, 1, 32, 1, 40, 9, 34, 24, 10, 6, 84, 105,
        99, 107, 101, 116, 18, 14, 10, 6, 116, 105, 99, 107, 101, 116, 24, 1,
        32, 1, 40, 12, 34, 114, 10, 14, 70, 108, 105, 103, 104, 116, 69, 110,
        100, 112, 111, 105, 110, 116, 18, 45, 10, 6, 116, 105, 99, 107, 101, 116,
        24, 1, 32, 1, 40, 11, 50, 29, 46, 97, 114, 114, 111, 119, 46, 102,
        108, 105, 103, 104, 116, 46, 112, 114, 111, 116, 111, 99, 111, 108, 46, 84,
        105, 99, 107, 101, 116, 18, 49, 10, 8, 108, 111, 99, 97, 116, 105, 111,
        110, 24, 2, 32, 3, 40, 11, 50, 31, 46, 97, 114, 114, 111, 119, 46,
        102, 108, 105, 103, 104, 116, 46, 112, 114, 111, 116, 111, 99, 111, 108, 46,
        76, 111, 99, 97, 116, 105, 111, 110, 34, 236, 1, 10, 10, 70, 108, 105,
        103, 104, 116, 73, 110, 102, 111, 18, 14, 10, 6, 115, 99, 104, 101, 109,
        97, 24, 1, 32, 1, 40, 12, 18, 66, 10, 17, 102, 108, 105, 103, 104,
        116, 95, 100, 101, 115, 99, 114, 105, 112, 116, 111, 114, 24, 2, 32, 1,
        40, 11, 50, 39, 46, 97, 114, 114, 111, 119, 46, 102, 108, 105, 103, 104,
        116, 46, 112, 114, 111, 116, 111, 99, 111, 108, 46, 70, 108, 105, 103, 104,
        116, 68, 101, 115, 99, 114, 105, 112, 116, 111, 114, 18, 55, 10, 8, 101,
        110, 100, 112, 111, 105, 110, 116, 24, 3, 32, 3, 40, 11, 50, 37, 46,
        97, 114, 114, 111, 119, 46, 102, 108, 105, 103, 104, 116, 46, 112, 114, 111,
        116, 111, 99, 111, 108, 46, 70, 108, 105, 103, 104, 116, 69, 110, 100, 112,
        111, 105, 110, 116, 18, 21, 10, 13, 116, 111, 116, 97, 108, 95, 114, 101,
        99, 111, 114, 100, 115, 24, 4, 32, 1, 40, 3, 18, 19, 10, 11, 116,
        111, 116, 97, 108, 95, 98, 121, 116, 101, 115, 24, 5, 32, 1, 40, 3,
        18, 15, 10, 7, 111, 114, 100, 101, 114, 101, 100, 24, 6, 32, 1, 40,
        8, 18, 20, 10, 12, 97, 112, 112, 95, 109, 101, 116, 97, 100, 97, 116,
        97, 24, 7, 32, 1, 40, 12, 34, 30, 10, 8, 67, 114, 105, 116, 101,
        114, 105, 97, 18, 18, 10, 10, 101, 120, 112, 114, 101, 115, 115, 105, 111,
        110, 24, 1, 32, 1, 40, 12, 34, 143, 1, 10, 10, 70, 108, 105, 103,
        104, 116, 68, 97, 116, 97, 18, 66, 10, 17, 102, 108, 105, 103, 104, 116,
        95, 100, 101, 115, 99, 114, 105, 112, 116, 111, 114, 24, 1, 32, 1, 40,
        11, 50, 39, 46, 97, 114, 114, 111, 119, 46, 102, 108, 105, 103, 104, 116,
        46, 112, 114, 111, 116, 111, 99, 111, 108, 46, 70, 108, 105, 103, 104, 116,
        68, 101, 115, 99, 114, 105, 112, 116, 111, 114, 18, 19, 10, 11, 100, 97,
        116, 97, 95, 104, 101, 97, 100, 101, 114, 24, 2, 32, 1, 40, 12, 18,
        20, 10, 12, 97, 112, 112, 95, 109, 101, 116, 97, 100, 97, 116, 97, 24,
        3, 32, 1, 40, 12, 18, 18, 10, 9, 100, 97, 116, 97, 95, 98, 111,
        100, 121, 24, 232, 7, 32, 1, 40, 12, 34, 30, 10, 12, 83, 99, 104,
        101, 109, 97, 82, 101, 115, 117, 108, 116, 18, 14, 10, 6, 115, 99, 104,
        101, 109, 97, 24, 1, 32, 1, 40, 12, 50, 205, 3, 10, 13, 70, 108,
        105, 103, 104, 116, 83, 101, 114, 118, 105, 99, 101, 18, 98, 10, 9, 72,
        97, 110, 100, 115, 104, 97, 107, 101, 18, 39, 46, 97, 114, 114, 111, 119,
        46, 102, 108, 105, 103, 104, 116, 46, 112, 114, 111, 116, 111, 99, 111, 108,
        46, 72, 97, 110, 100, 115, 104, 97, 107, 101, 82, 101, 113, 117, 101, 115,
        116, 26, 40, 46, 97, 114, 114, 111, 119, 46, 102, 108, 105, 103, 104, 116,
        46, 112, 114, 111, 116, 111, 99, 111, 108, 46, 72, 97, 110, 100, 115, 104,
        97, 107, 101, 82, 101, 115, 112, 111, 110, 115, 101, 40, 1, 48, 1, 18,
        83, 10, 11, 76, 105, 115, 116, 70, 108, 105, 103, 104, 116, 115, 18, 31,
        46, 97, 114, 114, 111, 119, 46, 102, 108, 105, 103, 104, 116, 46, 112, 114,
        111, 116, 111, 99, 111, 108, 46, 67, 114, 105, 116, 101, 114, 105, 97, 26,
        33, 46, 97, 114, 114, 111, 119, 46, 102, 108, 105, 103, 104, 116, 46, 112,
        114, 111, 116, 111, 99, 111, 108, 46, 70, 108, 105, 103, 104, 116, 73, 110,
        102, 111, 48, 1, 18, 91, 10, 13, 71, 101, 116, 70, 108, 105, 103, 104,
        116, 73, 110, 102, 111, 18, 39, 46, 97, 114, 114, 111, 119, 46, 102, 108,
        105, 103, 104, 116, 46, 112, 114, 111, 116, 111, 99, 111, 108, 46, 70, 108,
        105, 103, 104, 116, 68, 101, 115, 99, 114, 105, 112, 116, 111, 114, 26, 33,
        46, 97, 114, 114, 111, 119, 46, 102, 108, 105, 103, 104, 116, 46, 112, 114,
        111, 116, 111, 99, 111, 108, 46, 70, 108, 105, 103, 104, 116, 73, 110, 102,
        111, 18, 89, 10, 9, 71, 101, 116, 83, 99, 104, 101, 109, 97, 18, 39,
        46, 97, 114, 114, 111, 119, 46, 102, 108, 105, 103, 104, 116, 46, 112, 114,
        111, 116, 111, 99, 111, 108, 46, 70, 108, 105, 103, 104, 116, 68, 101, 115,
        99, 114, 105, 112, 116, 111, 114, 26, 35, 46, 97, 114, 114, 111, 119, 46,
        102, 108, 105, 103, 104, 116, 46, 112, 114, 111, 116, 111, 99, 111, 108, 46,
        83, 99, 104, 101, 109, 97, 82, 101, 115, 117, 108, 116, 18, 75, 10, 5,
        68, 111, 71, 101, 116, 18, 29, 46, 97, 114, 114, 111, 119, 46, 102, 108,
        105, 103, 104, 116, 46, 112, 114, 111, 116, 111, 99, 111, 108, 46, 84, 105,
        99, 107, 101, 116, 26, 33, 46, 97, 114, 114, 111, 119, 46, 102, 108, 105,
        103, 104, 116, 46, 112, 114, 111, 116, 111, 99, 111, 108, 46, 70, 108, 105,
        103, 104, 116, 68, 97, 116, 97, 48, 1, 98, 6, 112, 114, 111, 116, 111,
        51,
    ]
    return out^


# service FlightService RPC paths
comptime FLIGHTSERVICE_HANDSHAKE_PATH: StaticString = "/arrow.flight.protocol.FlightService/Handshake"
comptime FLIGHTSERVICE_LISTFLIGHTS_PATH: StaticString = "/arrow.flight.protocol.FlightService/ListFlights"
comptime FLIGHTSERVICE_GETFLIGHTINFO_PATH: StaticString = "/arrow.flight.protocol.FlightService/GetFlightInfo"
comptime FLIGHTSERVICE_GETSCHEMA_PATH: StaticString = "/arrow.flight.protocol.FlightService/GetSchema"
comptime FLIGHTSERVICE_DOGET_PATH: StaticString = "/arrow.flight.protocol.FlightService/DoGet"


trait FlightServiceServer(Copyable, Movable):
    """Typed server surface for the ``FlightService`` gRPC service."""

    def handshake(mut self, ctx: GrpcCallContext, requests: List[HandshakeRequest]) raises -> List[HandshakeResponse]:
        ...

    def list_flights(mut self, ctx: GrpcCallContext, request: Criteria) raises -> List[FlightInfo]:
        ...

    def get_flight_info(mut self, ctx: GrpcCallContext, request: FlightDescriptor) raises -> FlightInfo:
        ...

    def get_schema(mut self, ctx: GrpcCallContext, request: FlightDescriptor) raises -> SchemaResult:
        ...

    def do_get(mut self, ctx: GrpcCallContext, request: Ticket) raises -> List[FlightData]:
        ...


@fieldwise_init
struct FlightService_Handshake_Adapter[H: Copyable & FlightServiceServer & ImplicitlyDestructible](GrpcBidiStreaming, Copyable, Movable):
    """Byte adapter mapping ``FlightService.Handshake`` onto the runtime GrpcBidiStreaming trait."""
    var handler: Self.H

    def serve_bidi(mut self, ctx: GrpcCallContext, messages: List[List[UInt8]]) raises -> GrpcServerStreamReply:
        var reqs = List[HandshakeRequest]()
        for i in range(len(messages)):
            reqs.append(HandshakeRequest.decode(Span[UInt8, _](messages[i])))
        var outs = self.handler.handshake(ctx, reqs^)
        var raw = List[List[UInt8]]()
        for i in range(len(outs)):
            raw.append(outs[i].encode())
        return GrpcServerStreamReply.ok(raw^)


@fieldwise_init
struct FlightService_ListFlights_Adapter[H: Copyable & FlightServiceServer & ImplicitlyDestructible](GrpcServerStreaming, Copyable, Movable):
    """Byte adapter mapping ``FlightService.ListFlights`` onto the runtime GrpcServerStreaming trait."""
    var handler: Self.H

    def serve_server_streaming(mut self, ctx: GrpcCallContext, request_bytes: Span[UInt8, _]) raises -> GrpcServerStreamReply:
        var req = Criteria.decode(request_bytes)
        var outs = self.handler.list_flights(ctx, req)
        var raw = List[List[UInt8]]()
        for i in range(len(outs)):
            raw.append(outs[i].encode())
        return GrpcServerStreamReply.ok(raw^)


@fieldwise_init
struct FlightService_GetFlightInfo_Adapter[H: Copyable & FlightServiceServer & ImplicitlyDestructible](GrpcUnary, Copyable, Movable):
    """Byte adapter mapping ``FlightService.GetFlightInfo`` onto the runtime GrpcUnary trait."""
    var handler: Self.H

    def serve_unary(mut self, ctx: GrpcCallContext, request_bytes: Span[UInt8, _]) raises -> GrpcUnaryReply:
        var req = FlightDescriptor.decode(request_bytes)
        var out = self.handler.get_flight_info(ctx, req)
        return GrpcUnaryReply.ok(out.encode())


@fieldwise_init
struct FlightService_GetSchema_Adapter[H: Copyable & FlightServiceServer & ImplicitlyDestructible](GrpcUnary, Copyable, Movable):
    """Byte adapter mapping ``FlightService.GetSchema`` onto the runtime GrpcUnary trait."""
    var handler: Self.H

    def serve_unary(mut self, ctx: GrpcCallContext, request_bytes: Span[UInt8, _]) raises -> GrpcUnaryReply:
        var req = FlightDescriptor.decode(request_bytes)
        var out = self.handler.get_schema(ctx, req)
        return GrpcUnaryReply.ok(out.encode())


@fieldwise_init
struct FlightService_DoGet_Adapter[H: Copyable & FlightServiceServer & ImplicitlyDestructible](GrpcServerStreaming, Copyable, Movable):
    """Byte adapter mapping ``FlightService.DoGet`` onto the runtime GrpcServerStreaming trait."""
    var handler: Self.H

    def serve_server_streaming(mut self, ctx: GrpcCallContext, request_bytes: Span[UInt8, _]) raises -> GrpcServerStreamReply:
        var req = Ticket.decode(request_bytes)
        var outs = self.handler.do_get(ctx, req)
        var raw = List[List[UInt8]]()
        for i in range(len(outs)):
            raw.append(outs[i].encode())
        return GrpcServerStreamReply.ok(raw^)


@fieldwise_init
struct FlightServiceClient(Copyable, Movable):
    """Typed client stub for ``FlightService``; wraps GrpcClient."""
    var base_url: String

    def handshake(self) raises -> GrpcBidiStream:
        var c = GrpcClient(self.base_url)
        return c.call_bidi(String(FLIGHTSERVICE_HANDSHAKE_PATH))

    def list_flights(self, request: Criteria) raises -> GrpcServerStream:
        var c = GrpcClient(self.base_url)
        return c.call_server_streaming(String(FLIGHTSERVICE_LISTFLIGHTS_PATH), Span[UInt8, _](request.encode()))

    def get_flight_info(self, request: FlightDescriptor) raises -> FlightInfo:
        var c = GrpcClient(self.base_url)
        var res = c.call(String(FLIGHTSERVICE_GETFLIGHTINFO_PATH), Span[UInt8, _](request.encode()))
        return FlightInfo.decode(Span[UInt8, _](res.message))

    def get_schema(self, request: FlightDescriptor) raises -> SchemaResult:
        var c = GrpcClient(self.base_url)
        var res = c.call(String(FLIGHTSERVICE_GETSCHEMA_PATH), Span[UInt8, _](request.encode()))
        return SchemaResult.decode(Span[UInt8, _](res.message))

    def do_get(self, request: Ticket) raises -> GrpcServerStream:
        var c = GrpcClient(self.base_url)
        return c.call_server_streaming(String(FLIGHTSERVICE_DOGET_PATH), Span[UInt8, _](request.encode()))
